name: pipeline_01
description: ''
version: 0.0.1
author: marco.amhof@accenture.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: pipeline01
  parentArtefactID: marcoamhofaccenturecomteam
  buildSystem: wheel
  author: null
  createdAt: '2023-10-19 18:59:46'
pipelines:
  pipelines/pipeline_0101:
    name: pipeline_0101
    description: This pipeline graph reads data from two tables in a SQL Server database,
      namely SalesLT.Product and SalesLT.Customer, using the JDBC API. This allows
      for seamless integration of data from external sources into Spark for further
      analysis and processing.
    author: marco.amhof@accenture.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-19 18:59:46'
    datasets:
      inputs:
      - datasets/jdbc_customer
      - datasets/jdbc_salesorderheader
      outputs:
      - datasets/xlsOutput
    subgraphs: []
    dependencies: {}
datasets:
  datasets/jdbc_product:
    name: jdbc_product
    description: ''
    author: marco.amhof@accenture.com
    createdAt: '2023-10-19 19:36:36'
    mode: batch
    physicalDatasets:
      hslu_demo:
        fabricId: 6104
        datasetType: Warehouse
        description: ''
        author: marco.amhof@accenture.com
        createdAt: '2023-10-19 19:36:36'
  datasets/jdbc_customer:
    name: jdbc_customer
    description: ''
    author: marco.amhof@accenture.com
    createdAt: '2023-10-19 19:39:09'
    mode: batch
    physicalDatasets:
      hslu_demo:
        fabricId: 6104
        datasetType: Warehouse
        description: ''
        author: marco.amhof@accenture.com
        createdAt: '2023-10-19 19:39:09'
  datasets/jdbc_salesorderheader:
    name: jdbc_salesorderheader
    description: ''
    author: marco.amhof@accenture.com
    createdAt: '2023-10-19 19:42:11'
    mode: batch
    physicalDatasets:
      hslu_demo:
        fabricId: 6104
        datasetType: Warehouse
        description: ''
        author: marco.amhof@accenture.com
        createdAt: '2023-10-19 19:42:11'
  datasets/xlsOutput:
    name: xlsOutput
    description: ''
    author: marco.amhof@accenture.com
    createdAt: '2023-10-19 19:57:02'
    mode: batch
    physicalDatasets:
      hslu_demo:
        fabricId: 6104
        datasetType: File
        description: ''
        author: marco.amhof@accenture.com
        createdAt: '2023-10-19 19:57:02'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-10-19 18:59:46'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-10-19 18:59:28'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-19 18:59:28'
  '2333':
    projectUID: 2333
    projectName: ProphecySamples
    repositoryPath: gitUri=http://gitserver:3000/LfXQm6CO_team_1599/LfXQm6CO_project_2333.git&subPath=
    version: HelloWorld/1.1.0
    isDefault: false
    author: null
    createdAt: '2023-10-19 19:12:41'
pipelineConfigurations: {}
